# Generated by Django 4.0.3 on 2022-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notificationadmina'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoi',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='viacode',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
