# Generated by Django 4.0.3 on 2022-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_envoi_commission_viacode_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TendancePub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('description', models.TextField()),
            ],
        ),
    ]
