# Generated by Django 4.0.3 on 2022-03-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_tendancepub'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendancepub',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
