# Generated by Django 4.0.3 on 2022-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_depot_somme_alter_envoi_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='staf_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retrait',
            name='staf_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viacode',
            name='staf_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
