# Generated by Django 4.0.3 on 2022-03-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_verificationtransaction_nom_complet_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtransaction',
            name='reste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
