# Generated by Django 4.0.3 on 2022-03-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_verificationtransaction_reste'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtransaction',
            name='commission_incluse',
            field=models.BooleanField(default=False),
        ),
    ]
