# Generated by Django 4.0.3 on 2022-03-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_messages_nature_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='messages',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
