# Generated by Django 4.0.3 on 2022-03-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteprofessionnel',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
